export const ERROR_CODES = {
    // auth
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    UNAUTHORIZED: "UNAUTHORIZED",
    PASSWORD_REQUIRED: "PASSWORD_REQUIRED",
    LOGIN_REQUIRED: "LOGIN_REQUIRED",
    USER_DISABLED: "USER_DISABLED",

    // shared
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    NOT_FOUND: "NOT_FOUND",
    BAD_REQUEST: "BAD_REQUEST",

    // config
    INVALID_PAYLOAD: "INVALID_PAYLOAD",
    PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",

    //hmi
    INVALID_PROJECT_ID: "INVALID_PROJECT_ID",
}