export const ERROR_CODES = {
    // auth
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    USER_DISABLED: "USER_DISABLED",

    // shared
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    NOT_FOUND: "NOT_FOUND",
    INVALID_PAYLOAD: "INVALID_PAYLOAD",

    // config
    PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",

    //hmi
    INVALID_PROJECT_ID: "INVALID_PROJECT_ID",
    INVALID_PACKAGE: "INVALID_PACKAGE",
    PROJECT_ID_MISMATCH: "PROJECT_ID_MISMATCH",
}